# Generated by Django 4.1.2 on 2023-05-25 17:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("nudges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nudge_model",
            name="uid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
